### ISSUE TITLE
Recommendations for testing with vue-test-utils?

### ISSUE THREAD

**Issue by danielbachhuber** [cyon/vuex-pagination#28] opened 2020-11-24 15:59 UTC
Hi,

Do you have any recommendations for how to test for paginated data with vue-test-utils?

My typical test looks like this:

```js
it('mounts', async () => {
    expect.assertions(1);
    mock.onGet('/api-uri')
        .reply(200, JSON.stringify([
            firstItem,
            secondItem,
        ]), {'x-total-count': 2});
    wrapper = mount(
        Component,
        {
            localVue,
            router,
            store,
            mocks: {
                $route,
            },
            stubs: ['router-link', 'router-view']
        },
    );
    await flushPromises();
    await wrapper.vm.$nextTick();
});
```

However, the computed `createInstance()` seems stuck in the `.loading` state, even after I've flushed the promises and waited for a re-render.

Any ideas on what I might be doing wrong?

Thanks!

**Comment by danielbachhuber** [comment] 2020-12-07 23:38
@MaxGfeller Any ideas here? Thanks!

**Comment by MaxGfeller** [comment] 2020-12-28 14:54
Hi @danielbachhuber, sorry for only getting back to you now.

That's a good question. Does the component actually get mounted? Because the Vue plugin does the wiring in the `beforeMount` hook.

And where do you set up the store?

**Comment by danielbachhuber** [comment] 2020-12-28 15:03
> That's a good question. Does the component actually get mounted? Because the Vue plugin does the wiring in the `beforeMount` hook.

Yep, the component is mounted. I can see the other HTML rendered by the component, but not the the HTML that would be rendered if Vuex Pagination items were present.

> And where do you set up the store?

In `beforeEach`:

```js
beforeEach(() => {
    mock = new MockAdapter(window.axios);
    product = importJsonMock('models/Product/slack');
    store = new Vuex.Store({
        state: {
            product,
        },
        actions,
        mutations,
    });
});
```

Also, I've added an `initializeResources()` to the test, which calls `createResource()`:

```js
it('mounts', async () => {
    expect.assertions(1);
    mock.onGet('/api-uri')
        .reply(200, JSON.stringify([
            firstItem,
            secondItem,
        ]), {'x-total-count': 2});
    initializeResources();
    wrapper = mount(
        Component,
        {
            localVue,
            router,
            store,
            mocks: {
                $route,
            },
            stubs: ['router-link', 'router-view']
        },
    );
    await flushPromises();
    await wrapper.vm.$nextTick();
});
```

**Comment by danielbachhuber** [comment] 2020-12-28 15:22
Interestingly, I added some debugging inside of `setInRegistry` and can see the items being set.

I also added some debug to the component itself. When `loading` is set to false, the items exist on the object as expected:

```js
export default {
    computed: {
        ...mapState({
            product: state => state.product,
        }),
        themes: createInstance('themes', {
            pageSize: 200,
            args() {
                return {
                    product: this.product,
                    search: this.filter.search,
                    status: this.filter.status,
                };
            }
        }),
        themesIsLoading() {
            return this.themes.loading;
        }
    },
    watch: {
        themesIsLoading(val) {
            console.log('themesIsLoading');
            console.log(val);
            console.log(this.themes.items);
        }
    }
}
```

So maybe the component isn't re-rendering when its computed state is changing?

**Comment by danielbachhuber** [comment] 2020-12-28 15:25
> So maybe the component isn't re-rendering when its computed state is changing?

Yep, this must be it. Force updating causes the test to pass.

```js
it('mounts', async () => {
    expect.assertions(1);
    mock.onGet('/api-uri')
        .reply(200, JSON.stringify([
            firstItem,
            secondItem,
        ]), {'x-total-count': 2});
    initializeResources();
    wrapper = mount(
        Component,
        {
            localVue,
            router,
            store,
            mocks: {
                $route,
            },
            stubs: ['router-link', 'router-view']
        },
    );
    await flushPromises();
    await wrapper.vm.$nextTick();
    await wrapper.vm.$forceUpdate();
});
```

**Comment by MaxGfeller** [comment] 2020-12-28 15:26
I remember vaguely that i once had a similar problem... 🤔 I think you can also access `wrapper.vm.themes.loading` directly in your test and it should be correct.

**Comment by danielbachhuber** [comment] 2020-12-28 15:34
> Yep, this must be it. Force updating causes the test to pass.

Hm, force updating worked once and now it no longer works 😦

**Comment by MaxGfeller** [comment] 2020-12-28 15:36
That sounds like a race condition. Does it work with directly checking `wrapper.vm.themes.loading`?

**Comment by danielbachhuber** [comment] 2020-12-28 15:39
> That sounds like a race condition.

Yeah, or some object mutation issue.

> Does it work with directly checking `wrapper.vm.themes.loading`

Oh, good catch. `wrapper.vm.themes.loading` is still true immediately prior to the failed assertion.

I thought all of my `await` statements would be sufficient? Do you think there's something else I should try?

**Comment by MaxGfeller** [comment] 2020-12-28 15:48
You can try more `await` statements🙈 Sorry, not sure how many ticks are required.

**Comment by danielbachhuber** [comment] 2020-12-28 16:08
> You can try more `await` statements🙈 Sorry, not sure how many ticks are required.

Hm, this doesn't seem to work either:

```js
it('mounts', async () => {
    expect.assertions(1);
    mock.onGet('/api-uri')
        .reply(200, JSON.stringify([
            firstItem,
            secondItem,
        ]), {'x-total-count': 2});
    initializeResources();
    wrapper = mount(
        Component,
        {
            localVue,
            router,
            store,
            mocks: {
                $route,
            },
            stubs: ['router-link', 'router-view']
        },
    );
    await flushPromises();
    await new Promise(r => setTimeout(r, 1000));
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    await wrapper.vm.$nextTick();
    await wrapper.vm.$forceUpdate();
});
```

**Comment by danielbachhuber** [comment] 2020-12-29 12:07
@MaxGfeller Here's a repository that reproduces the issue: https://github.com/danielbachhuber/vuex-pagination-28

If you run `npm install && npm tdd`, you'll see output like this:

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/36432/103282491-d43cc900-498a-11eb-8c47-910f2b897e42.png">

Notably, here's how the `console.log()` debug ends up:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/36432/103282567-0f3efc80-498b-11eb-826e-7a0964d7c198.png">

**Comment by MaxGfeller** [comment] 2020-12-30 15:53
Thanks for the reproduction @danielbachhuber. I just had a look at it and got it to run.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/361435/103364665-b1133600-4abe-11eb-9ec2-8cb24a569144.png">

Here's what i did:
- There was a bug in the `Component.vue`, in the `v-for` it must be `themes.items` instead of `themes`
- The `flushPromises()` and `wrapper.vm.$forceUpdate()` are not necessary
- The magic number (for me at least) seems to be 7 `await wrapper.vm.$nextTick()` (i have no idea why it requires exactly that many ticks and you'd have to have an extensive look at how test-utils does the computation and rendering to find that out)
- I realize this is not very clean but it could be replaced with a `await new Promise(resolve => setTimeout(resolve, 50))`, too

Hope this helps.

**Comment by MaxGfeller** [comment] 2020-12-30 16:26
Even better solution: update to `1.3.9` and in your test replace all the awaits with `await wrapper.vm.$vuexPaginationInitialized`. 🎉 

Will document this in the README soon-ish.

**Comment by danielbachhuber** [comment] 2020-12-30 17:11
Thanks Max! I’ll check this out when I’m back at the computer in the next couple of days.

I thought I tried the setTimeout approach but maybe I missed something. My reproduction example was from scratch, so there might be a nuance of my main application that it missed. If it doesn’t fix, I’ll send you a short screencast of some further debugging.

Thanks again for your help!

**Comment by MaxGfeller** [comment] 2020-12-30 17:16
Sure thing! Problem was that the Vuex actions were not completed yet. That's why i added the `$vuexPaginationInitialized` property in the plugin: https://github.com/cyon/vuex-pagination/blob/master/src/index.js#L48

Please let me know if it works in your project, too.

**Comment by danielbachhuber** [comment] 2020-12-31 13:27
@MaxGfeller The plot thickens! I've found the real source of the problem I'm experiencing in my project though.

A component using Vuex pagination passes the assertions in the first `it()` test within `describe()` block. However, it will fail the same assertions in a second `it()` test in the same `describe()` block.

The reproduction repo is updated to document this behavior: https://github.com/danielbachhuber/vuex-pagination-28/commit/2e7d42ba4a70655d41bd5d07a9040e17acd3cc1d

I don't fully understand your store registration code is doing, but my guess is that `initializeStore` isn't getting reset: https://github.com/cyon/vuex-pagination/blob/33f08e23d717493b75e55f8dc5d5935e4c930b07/src/index.js#L40

**Comment by MaxGfeller** [comment] 2021-01-04 15:39
@danielbachhuber You are exactly right! In this case the store does not get reset.

I added a `reset()` function in `1.3.10`, which needs to called in the `afterEach()` block:

https://github.com/cyon/vuex-pagination/blob/master/src/index.js#L115-L119 

Hope that helps!

**Comment by danielbachhuber** [comment] 2021-01-04 21:17
Thanks @MaxGfeller ! `reset()` works great 🎉

**Comment by MaxGfeller** [comment] 2021-01-05 09:28
@danielbachhuber Awesome! I'm closing this issue then and provide documentation for those two small additions in a later version 👍🏻

**Closed by MaxGfeller** 2021-01-05 09:28 UTC
